include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - [build/**]
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    unnecessary_overrides: false
    prefer_const_constructors: false
    prefer_single_quotes: true
    prefer_const_literals_to_create_immutables: false