name: todolist_flutter_getx
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  
  # utils
  get: ^4.3.8
  get_storage: ^2.0.3
  sizer: ^2.0.15
  logger: ^1.1.0
  url_launcher: ^6.0.12

  # icons / themes
  cupertino_icons: ^1.0.2
  fluttericon: ^2.0.0
  flex_color_scheme: ^3.0.1


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

